# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: messaging.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'messaging.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fmessaging.proto\"4\n\x0eRequestAddUser\x12\x11\n\tuser_name\x18\x01 \x01(\t\x12\x0f\n\x07\x66ile_id\x18\x02 \x01(\t\"\x1d\n\x0fResponseAddUser\x12\n\n\x02id\x18\x01 \x01(\x05\"\x1b\n\x0bTextMessage\x12\x0c\n\x04text\x18\x01 \x01(\t\"\x1e\n\x0b\x46ileMessage\x12\x0f\n\x07\x66ile_id\x18\x01 \x01(\t\"\x1f\n\x0cImageMessage\x12\x0f\n\x07\x66ile_id\x18\x01 \x01(\t\"w\n\x0eMessageContent\x12\x1c\n\x04text\x18\x01 \x01(\x0b\x32\x0c.TextMessageH\x00\x12\x1c\n\x04\x66ile\x18\x02 \x01(\x0b\x32\x0c.FileMessageH\x00\x12\x1e\n\x05image\x18\x03 \x01(\x0b\x32\r.ImageMessageH\x00\x42\t\n\x07\x63ontent\"^\n\x12RequestSendMessage\x12\x11\n\tsender_id\x18\x01 \x01(\x05\x12\x13\n\x0breceiver_id\x18\x02 \x01(\x05\x12 \n\x07\x63ontent\x18\x03 \x01(\x0b\x32\x0f.MessageContent\"\x15\n\x13ResponseSendMessage\"!\n\x13RequestFetchMessage\x12\n\n\x02id\x18\x01 \x01(\x05\"8\n\x14ResponseFetchMessage\x12 \n\x07\x63ontent\x18\x03 \x01(\x0b\x32\x0f.MessageContent\"$\n\x16RequestGetUserMessages\x12\n\n\x02id\x18\x01 \x01(\x05\"<\n\x17ResponseGetUserMessages\x12!\n\x08\x63ontents\x18\x01 \x03(\x0b\x32\x0f.MessageContent2\xf6\x01\n\tMessaging\x12,\n\x07\x41\x64\x64User\x12\x0f.RequestAddUser\x1a\x10.ResponseAddUser\x12\x38\n\x0bSendMessage\x12\x13.RequestSendMessage\x1a\x14.ResponseSendMessage\x12;\n\x0c\x46\x65tchMessage\x12\x14.RequestFetchMessage\x1a\x15.ResponseFetchMessage\x12\x44\n\x0fGetUserMessages\x12\x17.RequestGetUserMessages\x1a\x18.ResponseGetUserMessagesB\x08Z\x06/grpc2b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'messaging_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\006/grpc2'
  _globals['_REQUESTADDUSER']._serialized_start=19
  _globals['_REQUESTADDUSER']._serialized_end=71
  _globals['_RESPONSEADDUSER']._serialized_start=73
  _globals['_RESPONSEADDUSER']._serialized_end=102
  _globals['_TEXTMESSAGE']._serialized_start=104
  _globals['_TEXTMESSAGE']._serialized_end=131
  _globals['_FILEMESSAGE']._serialized_start=133
  _globals['_FILEMESSAGE']._serialized_end=163
  _globals['_IMAGEMESSAGE']._serialized_start=165
  _globals['_IMAGEMESSAGE']._serialized_end=196
  _globals['_MESSAGECONTENT']._serialized_start=198
  _globals['_MESSAGECONTENT']._serialized_end=317
  _globals['_REQUESTSENDMESSAGE']._serialized_start=319
  _globals['_REQUESTSENDMESSAGE']._serialized_end=413
  _globals['_RESPONSESENDMESSAGE']._serialized_start=415
  _globals['_RESPONSESENDMESSAGE']._serialized_end=436
  _globals['_REQUESTFETCHMESSAGE']._serialized_start=438
  _globals['_REQUESTFETCHMESSAGE']._serialized_end=471
  _globals['_RESPONSEFETCHMESSAGE']._serialized_start=473
  _globals['_RESPONSEFETCHMESSAGE']._serialized_end=529
  _globals['_REQUESTGETUSERMESSAGES']._serialized_start=531
  _globals['_REQUESTGETUSERMESSAGES']._serialized_end=567
  _globals['_RESPONSEGETUSERMESSAGES']._serialized_start=569
  _globals['_RESPONSEGETUSERMESSAGES']._serialized_end=629
  _globals['_MESSAGING']._serialized_start=632
  _globals['_MESSAGING']._serialized_end=878
# @@protoc_insertion_point(module_scope)
